### ISSUE TITLE
Build error on phlib.lib using latest version of Visual Studio (17.5.2)

### ISSUE THREAD

**Issue by gui28347** [winsiderss/systeminformer#1652]
### Brief description of your issue

Using Visual Studio 17.5.1 I was able to compile all projects using build_debug.cmd

After upgrading to 17.5.2 it is now returning an erro: 

1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2242,30): error C3646: '_Mantissa_bits': unknown override specifier
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2242,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2243,30): error C3646: '_Exponent_bits': unknown override specifier
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2243,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2243,22): error C2086: 'const int std::_Floating_type_traits<float>::int32_t': redefinition
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2243,1): fatal  error C1903: unable to recover from previous error(s); stopping compilation
1>    0 Warning(s)
1>    6 Error(s)

### Steps to reproduce (optional)

Install visual studio 17.5.2
Run build_debug.cmd

### Expected behavior (optional)

Compile code

### Actual behavior (optional)

Error: 1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2242,30): error C3646: '_Mantissa_bits': unknown override specifier
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2242,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2243,30): error C3646: '_Exponent_bits': unknown override specifier
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2243,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2243,22): error C2086: 'const int std::_Floating_type_traits<float>::int32_t': redefinition
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\type_traits(2243,1): fatal  error C1903: unable to recover from previous error(s); stopping compilation
1>    0 Warning(s)
1>    6 Error(s)

**Comment by dmex** [comment]
The project doesn't use those headers and CI builds successfully:
https://user-images.githubusercontent.com/1306177/226534317-a15d66cb-38be-4ce0-abfd-f11ecc48e44b.png

Try deleting the source repository and checkout a fresh copy or repair visual studio?
https://learn.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2022

**Comment by gui28347** [comment]
I tried deleting the folder and git clone again, same error...
I use to build on prior versions with no issues... I see the CI works, but it still using 17.5.1 ...
Can you try on 17.5.2 ?

**Comment by gui28347** [comment]
it worked from different machine. Something machine related.

**Comment by gui28347** [comment]
To fix in the original machine, used "**REPAIR**" option in visual studio install. Tested again with 17.5.2 and newest 17.5.3 everything working just fine now.
