### ISSUE TITLE
build error on windows

### ISSUE THREAD

**Issue by pedoc** [winsiderss/systeminformer#1431]
### Brief description of your issue

After pulling the latest code, now it doesn't compile.

### Steps to reproduce (optional)

1. Clone this repo
2. Pull the latest code
3. Run ``.\build\build_release.cmd``,
The following error occurs(``C2220``):
![image](https://user-images.githubusercontent.com/6604230/196325167-6a15a964-96d9-4ff8-9cad-37fdebe9c553.png)

This issue was introduced by commit 2b38069d3de587bbc49285396cd7d90bcef3ae10, line 725

https://github.com/winsiderss/systeminformer/commit/2b38069d3de587bbc49285396cd7d90bcef3ae10?diff=split#diff-7ac1cdaada00d2d50932f4417c6c64a6827599da29cd46ab24fa856ef3b71a4dR725

### Expected behavior (optional)

Compile normally

### Actual behavior (optional)

Compilation failed

### Environment (optional)

```shell
Latest code on master branch
Windows 11 x64 22H2 (22623.746)
Visual studio 2022 17.3.6
```

**Comment by gui28347** [comment]
+1 
indows: 10.0.22621.674 (WinBuild.160101.0800)
WindowsSDK: 10.0.22000.0 (17.3.32708.82)
VisualStudio: VisualStudio/17.3.6+32929.385

Building... 3.0.9908.5381 (48a2e28) [master]

[00:00] Building SystemInformer (x32)...
[ERROR] (1) C:\source\processhacker\phlib\kphcomms.c(726): error C2220: the following warning is treated as an error [C:\source\processhacker\SystemInformer\SystemInformer.vcxproj]C:\source\processhacker\phlib\kphcomms.c(726): warning C4789: buffer 'reply' of size 4 bytes will be overrun; 3280 bytes will be written starting at offset 0 [C:\source\processhacker\SystemInformer\SystemInformer.vcxproj]C:\source\processhacker\phlib\kphcomms.c(726): error C4789: buffer 'reply' of size 4 bytes will be overrun; 3280 bytes will be written starting at offset 0 [C:\source\processhacker\SystemInformer\SystemInformer.vcxproj]LINK : fatal error LNK1257: code generation failed [C:\source\processhacker\SystemInformer\SystemInformer.vcxproj]

Compiling in Debug mode works, in release it fails.

**Comment by dmex** [comment]
The branch was out of sync. Thanks, fixed 👍
