### ISSUE TITLE
Compile time errors

### ISSUE THREAD

**Issue by trparky** [winsiderss/systeminformer#2166]
### Brief description of your issue

Compile time errors.

[ERROR] (1) C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(55,35): error C2146: syntax error: missing ')' before identifier 'Process' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(55,35): error C2061: syntax error: identifier 'Process' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(55,35): error C2059: syntax error: ';' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(55,42): error C2059: syntax error: ',' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(57,5): error C2059: syntax error: ')' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(61,35): error C2146: syntax error: missing ')' before identifier 'Entry' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(61,10): error C2081: 'PPH_ZOMBIE_PROCESS_ENTRY': name in formal parameter list illegal [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(61,35): error C2061: syntax error: identifier 'Entry' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(61,35): error C2059: syntax error: ';' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(62,5): error C2059: syntax error: ')' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(69,33): error C2061: syntax error: identifier 'ProcessesMethod' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(69,33): error C2059: syntax error: ';' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(190,29): error C2065: 'PPH_ZOMBIE_PROCESS_ENTRY': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(190,54): error C2146: syntax error: missing ';' before identifier 'entry' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(190,54): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(190,60): warning C4047: '=': 'int' differs in levels of indirection from 'PVOID' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(192,33): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(192,40): error C2223: left of '->FileName' must point to struct/union [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(193,53): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(193,60): error C2223: left of '->FileName' must point to struct/union [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(193,33): error C2198: 'void PhDereferenceObject(PVOID)': too few arguments for call [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(195,36): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(195,36): warning C4022: 'PhFree': pointer mismatch for actual parameter 1 [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(204,25): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(206,25): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(208,25): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(210,25): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(212,25): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(214,25): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(221,30): warning C4013: 'PhEnumZombieProcesses' undefined; assuming extern returning int [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(222,25): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(223,25): error C2065: 'PhpZombieProcessesCallback': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(245,21): error C2065: 'PPH_ZOMBIE_PROCESS_ENTRY': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(245,47): error C2065: 'entries': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(245,46): warning C4552: '*': result of expression not used [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(249,87): error C2065: 'entries': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(249,86): warning C4047: 'function': 'PVOID **' differs in levels of indirection from 'int *' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(249,86): warning C4022: 'PhGetSelectedListViewItemParams': pointer mismatch for actual parameter 2 [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(271,37): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(271,80): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(276,41): error C2065: 'entries': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(276,48): error C2109: subscript requires array or pointer type [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(273,46): error C2198: 'NTSTATUS PhOpenProcess(PHANDLE,ACCESS_MASK,HANDLE)': too few arguments for call [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(284,41): error C2065: 'entries': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(284,48): error C2109: subscript requires array or pointer type [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(281,46): error C2198: 'NTSTATUS PhOpenProcessByCsrHandles(PHANDLE,ACCESS_MASK,HANDLE)': too few arguments for call [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(313,28): error C2065: 'entries': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(313,28): warning C4022: 'PhFree': pointer mismatch for actual parameter 1 [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(351,33): error C2065: 'ProcessesMethod': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(365,37): error C2065: 'PPH_ZOMBIE_PROCESS_ENTRY': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(365,62): error C2146: syntax error: missing ';' before identifier 'entry' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(365,62): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(365,68): warning C4047: '=': 'int' differs in levels of indirection from 'PVOID' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(367,41): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(367,48): error C2223: left of '->Type' must point to struct/union [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(367,56): error C2065: 'ZombieProcess': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(369,46): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(369,53): error C2223: left of '->Type' must point to struct/union [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(371,46): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(371,53): error C2223: left of '->Type' must point to struct/union [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(377,41): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(377,48): error C2223: left of '->FileName' must point to struct/union [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(378,41): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(378,41): error C2223: left of '->ProcessId' must point to struct/union [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(419,25): error C2065: 'PPH_ZOMBIE_PROCESS_ENTRY': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(419,50): error C2146: syntax error: missing ';' before identifier 'entry' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(419,50): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(421,25): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(421,31): warning C4047: '=': 'int' differs in levels of indirection from 'PVOID' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(423,29): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(427,47): warning C4013: 'PhpCreateProcessItemForZombieProcess' undefined; assuming extern returning int [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(427,93): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(427,45): warning C4047: '=': 'PPH_PROCESS_ITEM' differs in levels of indirection from 'int' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(429,33): warning C4013: 'SystemInformer_ShowProcessProperties' undefined; assuming extern returning int [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(546,5): error C2065: 'PPH_ZOMBIE_PROCESS_ENTRY': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(546,30): error C2146: syntax error: missing ';' before identifier 'entry' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(546,30): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(546,36): warning C4047: '=': 'int' differs in levels of indirection from 'PVOID' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(548,13): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(548,20): error C2223: left of '->Type' must point to struct/union [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(551,10): error C2065: 'ZombieProcess': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(561,35): error C2146: syntax error: missing ')' before identifier 'Process' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(561,35): error C2061: syntax error: identifier 'Process' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(561,35): error C2059: syntax error: ';' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(561,42): error C2059: syntax error: ',' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(563,5): error C2059: syntax error: ')' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(593,35): error C2146: syntax error: missing ')' before identifier 'Entry' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(593,10): error C2081: 'PPH_ZOMBIE_PROCESS_ENTRY': name in formal parameter list illegal [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(593,35): error C2061: syntax error: identifier 'Entry' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(593,35): error C2059: syntax error: ';' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(594,5): error C2059: syntax error: ')' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(595,1): error C2449: found '{' at file scope (missing function header?) [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(757,1): error C2059: syntax error: '}' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(879,5): error C2061: syntax error: identifier 'PPH_ENUM_ZOMBIE_PROCESSES_CALLBACK' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(882,1): error C2059: syntax error: '}' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(891,5): error C2065: 'PCSR_HANDLES_CONTEXT': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(891,26): error C2146: syntax error: missing ';' before identifier 'context' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(891,26): error C2065: 'context': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(891,34): warning C4047: '=': 'int' differs in levels of indirection from 'PVOID' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(895,5): error C2065: 'PH_ZOMBIE_PROCESS_ENTRY': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(895,29): error C2146: syntax error: missing ';' before identifier 'entry' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(895,29): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(897,5): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(897,11): error C2224: left of '.ProcessId' must have struct/union type [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(914,13): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(914,19): error C2224: left of '.FileName' must have struct/union type [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(915,13): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(915,19): error C2224: left of '.FileNameWin32' must have struct/union type [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(918,17): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(918,23): error C2224: left of '.Type' must have struct/union type [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(919,22): error C2065: 'context': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(919,48): error C2065: 'context': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(919,57): error C2223: left of '->Pids' must point to struct/union [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(919,33): error C2198: 'ULONG PhFindItemList(PPH_LIST,PVOID)': too few arguments for call [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(920,17): error C2065: 'entry': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\hidnproc.c(920,17): error C1003: error count exceeds 100; stopping compilation [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\mainwnd.c(2881,55): error C2065: 'ID_TOOLS_ZOMBIEPROCESSES': undeclared identifier [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\mainwnd.c(4257,95): warning C4133: 'function': incompatible types - from 'PWCH' to 'PPH_STRINGREF' [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\srvprv.c(256,16): error C2220: the following warning is treated as an error [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\Users\trpar\source\repos\systeminformer\SystemInformer\srvprv.c(256,16): warning C4028: formal parameter 1 different from declaration [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]

GIT bisect has narrowed the bug down to commit c67f73924 (Update PhReferenceServiceItem to STRINGREF)

**Comment by dmex** [comment]
+700 commit merge in progress.

**Comment by trparky** [comment]
Still an issue.

**Comment by jxy-s** [comment]
I've rewritten history to remove the bad commits and moved the WIP work from to `dmex-develop`.
